name: Scrape Data, Build and Upload Model
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Install jsonlines package
        run: pip install jsonlines


      - name: Run urlscrape spider
        working-directory: ./spider/spider/spiders
        run: scrapy runspider urlscrape.py

      - name: Run homegate spider and save output
        working-directory: ./spider/spider/spiders
        run: scrapy crawl homegate -o ../../file.jl

      - name: Import data to MongoDB
        working-directory: ./spider/downloads
        env:
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
        run: python mongo_import.py -c listings -i ../file.jl

      - name: Run model script
        working-directory: ./model
        env:
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
        run: python model.py

      - name: Save model to Azure Storage
        working-directory: ./model
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        run: python save.py